In [1]:
import torch

/mnt/d/Deakin/AlgorithmicAssurance/LevelSetEstimation/env/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x = torch.rand(20)
y = torch.rand(20)

In [3]:
x

tensor([0.9092, 0.3840, 0.7199, 0.2818, 0.0530, 0.0730, 0.2607, 0.6504, 0.8923,
        0.8406, 0.0609, 0.5189, 0.8646, 0.5293, 0.2380, 0.5047, 0.6101, 0.8691,
        0.0327, 0.7649])

In [4]:
y

tensor([0.8853, 0.3550, 0.3484, 0.2816, 0.7372, 0.8888, 0.8670, 0.6977, 0.5557,
        0.5846, 0.3015, 0.0231, 0.0419, 0.2020, 0.4933, 0.0353, 0.8651, 0.3858,
        0.9331, 0.8038])

In [6]:
(x > y).float()

tensor([1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
        0., 0.])